# Generated by Django 3.2 on 2023-07-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20230703_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='is_homologated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biddingfilter',
            name='is_homologated',
            field=models.BooleanField(default=False),
        ),
    ]
