# Generated by Django 3.2 on 2023-07-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230529_0416'),
        ('bidding', '0004_auto_20230703_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='login',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='received_email',
        ),
        migrations.CreateModel(
            name='PlatformLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('received_email', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='bidding.platform')),
            ],
        ),
    ]
