# Generated by Django 3.2 on 2023-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20230731_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='date_expiry_minutes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
