# Generated by Django 3.2 on 2023-08-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_bidding_date_expiry_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='date_expiry_minutes',
            new_name='price_record_expiration_date',
        ),
        migrations.AddField(
            model_name='biddingfile',
            name='source',
            field=models.CharField(blank=True, default='bidding', max_length=100, null=True),
        ),
    ]
