# Generated by Django 3.2 on 2023-08-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auto_20230816_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='object_bidding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
