# Generated by Django 3.2 on 2023-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_bidding_object_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingImported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('seq', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('cnpj', 'year', 'seq')},
            },
        ),
    ]
