# Generated by Django 3.2 on 2023-09-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0005_company_difference'),
        ('bidding', '0009_biddingimported'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding', to='company.company'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
