# Generated by Django 3.2 on 2023-09-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_auto_20230912_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingimported',
            name='bidding',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bidding.bidding'),
            preserve_default=False,
        ),
    ]
