# Generated by Django 3.2 on 2023-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_biddingimported_bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingfile',
            name='name',
            field=models.TextField(),
        ),
    ]
