# Generated by Django 3.2 on 2023-10-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_historicalbidding_historicalbiddingfile_historicalbiddingfilter_historicalbiddingimported_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
