# Generated by Django 3.2 on 2023-10-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0014_auto_20231023_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='link_pncp',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalbidding',
            name='link_pncp',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
