# Generated by Django 3.2 on 2023-10-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0015_auto_20231026_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbidding',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
