# Generated by Django 3.2 on 2023-11-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0016_auto_20231030_1812'),
        ('bidding', '0016_biddingcompanycertificate_biddingcompanyfile'),
    ]

    operations = [
    ]
