# Generated by Django 3.2 on 2023-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0017_merge_20231106_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingfilter',
            name='imported',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalbiddingfilter',
            name='imported',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
