# Generated by Django 3.2 on 2023-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_auto_20231109_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingitem',
            name='fob_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbiddingitem',
            name='fob_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
