# Generated by Django 3.2 on 2023-12-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_auto_20231109_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingcompanycertificate',
            name='bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='biddingcompanyfile',
            name='bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.bidding'),
        ),
    ]
