# Generated by Django 3.2 on 2023-12-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0019_auto_20231201_1431'),
        ('bidding', '0019_auto_20231205_1733'),
    ]

    operations = [
    ]
