# Generated by Django 3.2 on 2024-04-10 18:59

from django.db import migrations, models
import django.db.models.deletion

def populate_phase(apps, schema_editor):
    Bidding = apps.get_model('bidding', 'Bidding')
    for bidding in Bidding.objects.all():
        bidding.phase = bidding.status.phase
        bidding.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0020_merge_0019_auto_20231201_1431_0019_auto_20231205_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bidding.phase'),
            preserve_default=False,
        ),

        migrations.RunPython(populate_phase),
        
        migrations.AddField(
            model_name='historicalbidding',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.phase'),
        ),
    ]
