# Generated by Django 3.2 on 2024-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0021_auto_20240410_1859'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['trade_number'], name='bidding_bid_trade_n_6058d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['uasg'], name='bidding_bid_uasg_b00bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['date'], name='bidding_bid_date_1482a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['-date'], name='bidding_bid_date_947225_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['bidding_hour'], name='bidding_bid_bidding_bb95fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['date_capture'], name='bidding_bid_date_ca_6271bb_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['date_proposal'], name='bidding_bid_date_pr_18361e_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['hour_proposal'], name='bidding_bid_hour_pr_8ee6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['is_homologated'], name='bidding_bid_is_homo_f41ef7_idx'),
        ),
    ]
