# Generated by Django 3.2 on 2024-04-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0022_auto_20240412_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatform',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
