# Generated by Django 3.2 on 2024-06-10 01:46

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
import simple_history.models

from apps.bidding.models import (
    BiddingType,
)

from apps.accounts.models import (
    Account,
)

def copy_type(apps, schema_editor):
    Type = apps.get_model('bidding', 'Type')
    #Account = apps.get_model('accounts', 'Account')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE bidding_biddingtype DISABLE TRIGGER ALL;")

        account_instance = Account.objects.get(id=1)

        for type_obj in Type.objects.all():
            BiddingType.objects.create(id=type_obj.id,
                                       name=type_obj.name,
                                       account=account_instance)

        cursor.execute("ALTER TABLE bidding_biddingtype ENABLE TRIGGER ALL;")
                            

class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20240523_0520'),
        ('accounts', '0009_alter_account_managers'),
        ('product', '0009_auto_20240524_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0010_alter_companycertificatestatus_managers'),
        ('client', '0004_auto_20240531_0132'),
        ('bidding', '0023_auto_20240412_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBiddingType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical bidding type',
                'verbose_name_plural': 'historical bidding types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='history_user',
        ),
        migrations.AlterModelManagers(
            name='bidding',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingcompanycertificate',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingcompanyfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingimported',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingitem',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='biddingitemcompound',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dispute',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='interest',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modality',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='phase',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='platform',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='platformlogin',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='requirement',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='status',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='bidding',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Bidding', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingcompanycertificate',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingCompanyCertificate', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingcompanyfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingCompanyFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingimported',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingImported', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingitem',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingItem', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingitemcompound',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingItemCompound', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispute',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_dispute', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbidding',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalbiddingfile',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalbiddingfilter',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalbiddingimported',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalbiddingitem',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalbiddingitemcompound',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicaldispute',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalinterest',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalmodality',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalphase',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalplatform',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalplatformlogin',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalrequirement',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='interest',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_interest', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modality',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_modality', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_phase', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_platform', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformlogin',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BiddingPlatformLogin', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_requirement', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_status', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaldispute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalinterest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalmodality',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalphase',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplatform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modality',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='biddingcompanycertificate',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='biddingcompanyfile',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='biddingfile',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='biddingimported',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='biddingitem',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='biddingitemcompound',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='platformlogin',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bidding',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_id_account'),
        ),
        migrations.AddConstraint(
            model_name='bidding',
            constraint=models.UniqueConstraint(fields=('uasg', 'trade_number', 'account'), name='unique_bidding_ruasg_tradenumber_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_biddingfilter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_biddingfilter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingimported',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_biddingimported_id_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingimported',
            constraint=models.UniqueConstraint(fields=('cnpj', 'year', 'seq', 'account'), name='unique_biddingimported_cnpj_year_seq_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingitemcompound',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_biddingitemcompound_id_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingitemcompound',
            constraint=models.UniqueConstraint(fields=('item', 'product', 'account'), name='unique_biddingitemcompound_item_prod_account'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_dispute_id_account'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_dispute_name_account'),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_interest_id_account'),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_interest_name_account'),
        ),
        migrations.AddConstraint(
            model_name='modality',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_modality_id_account'),
        ),
        migrations.AddConstraint(
            model_name='modality',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_modality_name_account'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_phase_id_account'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_phase_name_account'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_platform_id_account'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_platform_name_account'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_requirement_id_account'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_requirement_name_account'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_status_id_account'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('name', 'phase'), name='unique_bidding_status_name_phase'),
        ),
        migrations.AddField(
            model_name='historicalbiddingtype',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalbiddingtype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biddingtype',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_type', to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='biddingtype',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_bidding_type_id_account'),
        ),
        migrations.AddConstraint(
            model_name='biddingtype',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_bidding_type_name_account'),
        ),

        migrations.RunPython(copy_type),

        migrations.AlterField(
            model_name='bidding',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidding', to='client.client'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding', to='company.company'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='dispute',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.dispute'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='freight_group',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.freight'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.interest'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='modality',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.modality'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='phase',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='platform',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.status'),
        ),
        migrations.AlterField(
            model_name='biddingcompanycertificate',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BiddingCompanyCertificate', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='biddingcompanycertificate',
            name='document',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.companycertificate'),
        ),
        migrations.AlterField(
            model_name='biddingcompanyfile',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='biddingcompanyfile',
            name='document',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.companyfile'),
        ),
        migrations.AlterField(
            model_name='biddingfile',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='client.client'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='company.company'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='dispute',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bidding.dispute'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='freight_group',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.freight'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='bidding.interest'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='modality',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='bidding.modality'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='phase',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='platform',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='bidding.status'),
        ),
        migrations.AlterField(
            model_name='biddingimported',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BiddingImported', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='biddingitem',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='biddingitem',
            name='parent',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bidding.biddingitem'),
        ),
        migrations.AlterField(
            model_name='biddingitemcompound',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='bidding.biddingitem'),
        ),
        migrations.AlterField(
            model_name='biddingitemcompound',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='dispute',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.dispute'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='freight_group',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.freight'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.interest'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='modality',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.modality'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='phase',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='platform',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.status'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfile',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='dispute',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.dispute'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='freight_group',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.freight'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.interest'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='modality',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.modality'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='phase',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='platform',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.status'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingimported',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingitem',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingitem',
            name='parent',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingitem'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingitemcompound',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingitem'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingitemcompound',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AlterField(
            model_name='historicalplatformlogin',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalplatformlogin',
            name='platform',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='phase',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='platformlogin',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='platformlogin',
            name='platform',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='status',
            name='phase',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingtype'),
        ),
        migrations.AlterField(
            model_name='biddingfilter',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding_filter', to='bidding.biddingtype'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingtype'),
        ),
        migrations.AlterField(
            model_name='historicalbiddingfilter',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingtype'),
        ),
        migrations.DeleteModel(
            name='HistoricalType',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
