# Generated by Django 3.2 on 2024-06-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0024_auto_20240610_0146'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_trade_n_6058d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_uasg_b00bdb_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_date_1482a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_date_947225_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_bidding_bb95fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_date_ca_6271bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_date_pr_18361e_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_hour_pr_8ee6e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='bidding',
            name='bidding_bid_is_homo_f41ef7_idx',
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'trade_number'], name='bidding_bid_account_9d1608_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'uasg'], name='bidding_bid_account_660fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'date'], name='bidding_bid_account_d110e0_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', '-date'], name='bidding_bid_account_8859bb_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'bidding_hour'], name='bidding_bid_account_80a8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'date_capture'], name='bidding_bid_account_ef07b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'date_proposal'], name='bidding_bid_account_b022d1_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'hour_proposal'], name='bidding_bid_account_24c331_idx'),
        ),
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account', 'is_homologated'], name='bidding_bid_account_3ee835_idx'),
        ),
    ]
