# Generated by Django 3.2 on 2024-06-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0025_auto_20240610_0437'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='status',
            name='unique_bidding_status_name_phase',
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('name', 'phase', 'account'), name='unique_bidding_status_name_phase_account'),
        ),
    ]
