# Generated by Django 3.2 on 2024-06-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0026_auto_20240610_0449'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['account', 'id'], name='bidding_sta_account_dc4c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['account', 'phase'], name='bidding_sta_account_9caea4_idx'),
        ),
    ]
