# Generated by Django 3.2 on 2024-06-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0027_auto_20240610_0455'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bidding',
            index=models.Index(fields=['account'], name='bidding_bid_account_c5846e_idx'),
        ),
    ]
