# Generated by Django 3.2 on 2024-06-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20240523_0520'),
        ('company', '0010_alter_companycertificatestatus_managers'),
        ('client', '0004_auto_20240531_0132'),
        ('bidding', '0028_bidding_bidding_bid_account_c5846e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidding', to='client.client'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidding', to='company.company'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='freight_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.freight'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.interest'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.modality'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.status'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingtype'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='freight_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.freight'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='interest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.interest'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='modality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.modality'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.phase'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='platform',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.platform'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.status'),
        ),
        migrations.AlterField(
            model_name='historicalbidding',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingtype'),
        ),
    ]
