# Generated by Django 3.2 on 2024-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0029_auto_20240610_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='is_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biddingfilter',
            name='is_filed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalbidding',
            name='is_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbiddingfilter',
            name='is_filed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
