# Generated by Django 3.2 on 2023-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='complement',
            field=models.CharField(blank=True, max_length=1050, null=True, verbose_name='complement'),
        ),
    ]
