# Generated by Django 3.2 on 2024-04-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_auto_20231207_2014'),
        ('accounts', '0004_auto_20240412_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='permission.profilepermissions'),
        ),
    ]
