# Generated by Django 3.2 on 2024-05-17 14:41

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields
import django_multitenant.models

def add_account_master(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')

    if not Account.objects.exists():
        Account.objects.create(name='SysLic Master', is_master=True)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240506_1223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'cnpj')},
        ),

        migrations.RunPython(add_account_master),

        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='context_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='context_account', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='accounts.account'),
            preserve_default=False,
        ),
    ]
