# Generated by Django 3.2 on 2024-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20231129_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file_name',
            field=models.TextField(),
        ),
    ]
