# Generated by Django 3.2 on 2024-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('product', '0005_alter_productfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_classifier', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unity',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_unity', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warranty',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_warranty', to='accounts.account'),
            preserve_default=False,
        ),
    ]
