# Generated by Django 3.2 on 2024-05-18 00:17

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('supplier', '0007_auto_20240517_2343'),
        ('product', '0006_auto_20240517_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classifier',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materiallist',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='type',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unity',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='warranty',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductImage', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiallist',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMaterialList', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classifier',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductClassifier', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='classifier',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='materiallist',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='productfile',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='unity',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='warranty',
            unique_together={('id', 'account')},
        ),
        migrations.AlterField(
            model_name='product',
            name='classifier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.classifier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unity',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.unity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.warranty'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='product.product'),
        ),
        migrations.AlterField(
            model_name='type',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductType', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductUnity', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductWarranty', to='accounts.account'),
        ),
    ]
