# Generated by Django 3.2 on 2024-05-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20240518_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unity',
            name='symbol',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unity',
            name='unity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='classifier',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_classifier_id_account'),
        ),
        migrations.AddConstraint(
            model_name='classifier',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_classifier_name_account'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_product_id_account'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('model', 'account'), name='unique_product_model_account'),
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_type_id_account'),
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_type_name_account'),
        ),
        migrations.AddConstraint(
            model_name='unity',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_unity_id_account'),
        ),
        migrations.AddConstraint(
            model_name='unity',
            constraint=models.UniqueConstraint(fields=('unity', 'account'), name='unique_unity_unity_account'),
        ),
        migrations.AddConstraint(
            model_name='unity',
            constraint=models.UniqueConstraint(fields=('symbol', 'account'), name='unique_unity_symbol_account'),
        ),
        migrations.AddConstraint(
            model_name='warranty',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_warranty_id_account'),
        ),
        migrations.AddConstraint(
            model_name='warranty',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_warranty_name_account'),
        ),
    ]
