# Generated by Django 3.2 on 2024-05-24 20:03

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20240523_0515'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classifier',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='type',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unity',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='warranty',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
