# Generated by Django 3.2 on 2023-12-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_complement'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('profile', 'tag')},
        ),
    ]
