# Generated by Django 3.2 on 2023-12-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_alter_metadata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=set(),
        ),
    ]
