# Generated by Django 3.2 on 2024-05-23 23:27

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_managers'),
        ('metadata', '0003_alter_metadata_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='metadata',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MetaData', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_metadata_id_account'),
        ),
    ]
