# Generated by Django 3.2 on 2023-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
