# Generated by Django 3.2 on 2023-07-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevisualization',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='messager.message'),
        ),
    ]
