# Generated by Django 3.2 on 2024-05-23 23:11

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_managers'),
        ('messager', '0002_alter_messagevisualization_message'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='messagevisualization',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Message', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagevisualization',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MessageVisualization', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_message_id_account'),
        ),
        migrations.AddConstraint(
            model_name='messagevisualization',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_message_visualization_id_account'),
        ),
        migrations.AlterField(
            model_name='messagevisualization',
            name='message',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='messager.message'),
        ),
    ]
