# Generated by Django 3.2 on 2024-05-18 00:27

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('transport', '0006_auto_20240517_2343'),
        ('client', '0002_alter_client_complement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='region_freight',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.freight'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('id', 'account')},
        ),
    ]
