# Generated by Django 3.2 on 2023-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='complement',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
    ]
