# Generated by Django 3.2 on 2024-05-23 05:27

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_managers'),
        ('client', '0003_auto_20240518_0027'),
        ('contact', '0002_alter_contact_complement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Contact', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='client.client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='company.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='supplier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='supplier.supplier'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contact_id_account'),
        ),
    ]
