# Generated by Django 3.2 on 2024-05-31 00:29

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20240523_0520'),
        ('contact', '0003_auto_20240523_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='transport.carrier'),
        ),
    ]
