# Generated by Django 3.2 on 2023-10-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_commission'),
        ('order', '0028_merge_0027_auto_20231009_1735_0027_auto_20231011_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released')], default='pending', max_length=100)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdelivery')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='accounts.profile')),
            ],
        ),
    ]
