# Generated by Django 3.2 on 2023-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('payed', 'Payed')], default='pending', max_length=100),
        ),
    ]
