# Generated by Django 3.2 on 2023-10-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_merge_0027_auto_20231009_1735_0027_auto_20231011_2113'),
        ('accounts', '0002_profile_commission'),
        ('commission', '0002_alter_commission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_delivery', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_owner', to='accounts.profile'),
        ),
    ]
