# Generated by Django 3.2 on 2023-11-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_auto_20231017_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
