# Generated by Django 3.2 on 2023-12-15 19:02

from django.db import migrations, models
import django.db.models.deletion

def populate_commission_from_delivery(apps, schema_editor):

    Commission = apps.get_model('commission', 'Commission')

    for commission in Commission.objects.all():
        if commission:
            commission.commitment = commission.delivery.commitment
            commission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_historicalordercommitmentfile_ordercommitmentfile'),
        ('commission', '0004_commission_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_commitment', to='order.ordercommitment'),
            preserve_default=False,
        ),

        migrations.RunPython(populate_commission_from_delivery),

        migrations.AlterField(
            model_name='commission',
            name='commitment',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='order.ordercommitment'),
        ),

        migrations.RemoveField(
            name='delivery',
            model_name='commission',
        ),

    ]
