# Generated by Django 3.2 on 2024-01-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20240111_2048'),
        ('commission', '0005_populate_commission_from_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_commitment', to='order.ordercommitment'),
        ),
    ]
