# Generated by Django 3.2 on 2024-01-24 16:26

from django.db import migrations, models
import django.db.models.deletion

def populate_commission_from_invoicing(apps, schema_editor):

    Commission = apps.get_model('commission', 'Commission')
    OrderInvoicing = apps.get_model('order', 'OrderInvoicing')
    OrderInvoicingStatus = apps.get_model('order', 'OrderInvoicingStatus')

    OrderDeliveryItem = apps.get_model('order', 'OrderDeliveryItem')
    OrderDelivery = apps.get_model('order', 'OrderDelivery')

    for commission in Commission.objects.all():
        if commission:
            status_queryset = OrderInvoicingStatus.objects.filter(initial=True)

            status_initial = ''

            if status_queryset.exists():
                status_initial = status_queryset.first()
            else:
                status_initial = OrderInvoicingStatus.objects.create(name='Faturamento em Analise',
                                                                      color='#808080',
                                                                      initial=True)

            situation = 'released'
            if commission.commitment.real_pay_date:
                situation = 'done'

            items_queryset = OrderDeliveryItem.objects.filter(item__commitment=commission.commitment)

            delivery_list = items_queryset.values('delivery').distinct()

            for obj in delivery_list:
                delivery_instance = OrderDelivery.objects.get(id=obj['delivery'])

                invoincing_queryset = OrderInvoicing.objects.filter(commitment=commission.commitment, delivery=delivery_instance)
                invoicing = ''

                if invoincing_queryset.exists():
                    invoicing = invoincing_queryset.first()
                else:
                    invoicing = OrderInvoicing.objects.create(
                        commitment=commission.commitment,
                        delivery=delivery_instance,
                        note_number=commission.commitment.note_number,
                        invoicing_date=commission.commitment.billing_date,
                        expected_payment_date=commission.commitment.pay_date,
                        real_pay_date=commission.commitment.real_pay_date,
                        annotation=commission.commitment.annotation_invoicing,
                        status=status_initial,
                        situation=situation
                    )

                commission.invoicing = invoicing
                commission.save()

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_auto_20240124_1626'),
        ('commission', '0006_alter_commission_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='invoicing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_invoicing', to='order.orderinvoicing'),
            preserve_default=False,
        ),

        migrations.RunPython(populate_commission_from_invoicing),

        migrations.RemoveField(
            model_name='commission',
            name='commitment',
        ),
    ]
