# Generated by Django 3.2 on 2024-01-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_auto_20240124_1626'),
        ('commission', '0007_auto_20240124_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='invoicing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoicing', to='order.orderinvoicing'),
            preserve_default=False,
        ),
    ]
