# Generated by Django 3.2 on 2024-05-24 01:01

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20240524_0024'),
        ('accounts', '0009_alter_account_managers'),
        ('commission', '0008_alter_commission_invoicing'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='commission',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='commission',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Commission', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='invoicing',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoicing', to='order.orderinvoicing'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_commission_id_account'),
        ),
    ]
