# Generated by Django 3.2 on 2023-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
