# Generated by Django 3.2 on 2023-10-25 14:25

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_carrier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
