# Generated by Django 3.2 on 2024-05-17 23:43

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('transport', '0005_alter_carrier_complement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carrier',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='freight',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='carrier',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Carrier', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freight',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Freight', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carrier',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='freight',
            unique_together={('id', 'account')},
        ),
    ]
