# Generated by Django 3.2 on 2024-05-23 05:20

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20240517_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freight',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_carrier_id_account'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(fields=('cnpj', 'account'), name='unique_carrier_cnpj_account'),
        ),
        migrations.AddConstraint(
            model_name='freight',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_freight_id_account'),
        ),
        migrations.AddConstraint(
            model_name='freight',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_freight_name_account'),
        ),
    ]
