# Generated by Django 3.2 on 2023-08-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230529_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfile',
            name='status',
        ),
        migrations.DeleteModel(
            name='CompanyFileStatus',
        ),
    ]
