# Generated by Django 3.2 on 2023-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20230814_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycertificatestatus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
