# Generated by Django 3.2 on 2023-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companycertificatestatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=20),
        ),
    ]
