# Generated by Django 3.2 on 2024-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycertificatefile',
            name='file_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='document_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='file_name',
            field=models.TextField(),
        ),
    ]
