# Generated by Django 3.2 on 2024-05-18 00:27

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('client', '0003_auto_20240518_0027'),
        ('company', '0007_auto_20240412_1905'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companycertificate',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companycertificatefile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companycertificatestatus',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companyfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyCertificate', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companycertificatefile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyCertificateFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companycertificatestatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyCertificateStatus', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='companycertificate',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='companycertificatefile',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='companycertificatestatus',
            unique_together={('id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='companyfile',
            unique_together={('id', 'account')},
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_client', to='client.client'),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_status', to='company.companycertificatestatus'),
        ),
        migrations.AlterField(
            model_name='companycertificatefile',
            name='certificate',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_files', to='company.companycertificate'),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_file', to='company.company'),
        ),
    ]
