# Generated by Django 3.2 on 2024-05-23 05:22

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20240518_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=50, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='companycertificatestatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_company_id_account'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('cnpj', 'account'), name='unique_company_cnpj_account'),
        ),
        migrations.AddConstraint(
            model_name='companycertificatestatus',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_company_certificate_id_account'),
        ),
        migrations.AddConstraint(
            model_name='companycertificatestatus',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_company_certicate_name_account'),
        ),
    ]
