# Generated by Django 3.2 on 2024-05-31 19:20

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20240523_0522'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companycertificatestatus',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
