# Generated by Django 3.2 on 2023-07-04 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230529_0416'),
        ('bidding', '0004_auto_20230703_2352'),
        ('order', '0002_auto_20230703_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date_delivery', models.DateField()),
                ('date_expiration', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCommitmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='bidding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='bidding.bidding'),
        ),
        migrations.CreateModel(
            name='OrderCommitmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordercommitment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.biddingitem')),
            ],
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='order.order'),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitmentstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='ordercommitment',
            unique_together={('order', 'number')},
        ),
    ]
