# Generated by Django 3.2 on 2023-07-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20230703_2352'),
        ('order', '0003_auto_20230704_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercommitmentitem',
            name='cost',
        ),
        migrations.AlterField(
            model_name='ordercommitmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingitem'),
        ),
        migrations.CreateModel(
            name='OrderCommitmentItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.ordercommitmentitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingitemcompound')),
            ],
        ),
    ]
