# Generated by Django 3.2 on 2023-07-31 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230724_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommitmentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_delivery', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitmentstatus')),
            ],
        ),
    ]
