# Generated by Django 3.2 on 2023-08-01 17:39

import apps.order.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('company', '0002_auto_20230529_0416'),
        ('transport', '0002_carrier'),
        ('order', '0005_ordercommitmentfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivery', models.DateField()),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=20, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.carrier')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='order.ordercommitment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.state')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderdelivery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitmentitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.order.models.OrderDeliveryFile.upload_to_path, validators=[apps.order.models.OrderDeliveryFile.validate_file_size])),
                ('name', models.CharField(max_length=100)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.orderdelivery')),
            ],
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderdeliverystatus'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together={('commitment', 'number')},
        ),
    ]
