# Generated by Django 3.2 on 2023-08-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20230801_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercommitmentitem',
            name='deliverable',
            field=models.BooleanField(default=False),
        ),
    ]
