# Generated by Django 3.2 on 2023-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordercommitmentitem_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together={('commitment', 'delivery_number')},
        ),
    ]
