# Generated by Django 3.2 on 2023-08-06 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_carrier'),
        ('order', '0008_auto_20230805_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryFreightCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'(99) 99999-9999'. Up to 15 digits allowed.", regex='^\\(\\d{2,}\\) \\d{4,5}\\-\\d{4}$')])),
                ('cost', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('date_cotation', models.DateField()),
                ('accepted', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.carrier')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='order.orderdelivery')),
            ],
        ),
    ]
