# Generated by Django 3.2 on 2023-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderdeliveryfreightcotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryfreightcotation',
            name='quote_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
