# Generated by Django 3.2 on 2023-08-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('order', '0010_orderdeliveryfreightcotation_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='trade_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
