# Generated by Django 3.2 on 2023-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20230815_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='annotation_invoicing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
