# Generated by Django 3.2 on 2023-08-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_carrier'),
        ('client', '0001_initial'),
        ('company', '0003_auto_20230814_1131'),
        ('order', '0012_auto_20230817_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('delivery_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_number', models.CharField(blank=True, max_length=100, null=True)),
                ('commitment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_delivery', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.carrier')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderdeliverystatus')),
            ],
        ),
    ]
