# Generated by Django 3.2 on 2023-08-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0003_auto_20230814_1131'),
        ('accounts', '0001_initial'),
        ('order', '0013_orderdeliveryfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('uasg', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_delivery_gte', models.DateField(blank=True, null=True)),
                ('date_delivery_lte', models.DateField(blank=True, null=True)),
                ('date_expiration_gte', models.DateField(blank=True, null=True)),
                ('date_expiration_lte', models.DateField(blank=True, null=True)),
                ('nf_payed', models.BooleanField(null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='client.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='company.company')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='order.orderinterest')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='accounts.profile')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='order.orderstatus')),
            ],
        ),
    ]
