# Generated by Django 3.2 on 2023-08-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20230823_0006'),
        ('order', '0014_orderfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bidding',
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='contract.contract'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercommitmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentitemproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractitemcompound'),
        ),
    ]
