# Generated by Django 3.2 on 2023-09-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20230918_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='invoicing_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryfilter',
            name='invoicing_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
