# Generated by Django 3.2 on 2023-09-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_historicalorder_historicalordercommitment_historicalordercommitmentitem_historicalordercommitmentite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderfilter',
            name='status',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderStatus',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
