# Generated by Django 3.2 on 2023-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_historicalorderassistance_historicalorderassistancestatus_historicalorderassistancetype_orderassista'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderassistance',
            name='date_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderassistance',
            name='date_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
