# Generated by Django 3.2 on 2023-09-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20230926_1658'),
        ('order', '0022_auto_20230928_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='payment_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='technician_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='payment_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancestatus'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancetype'),
        ),
    ]
