# Generated by Django 3.2 on 2023-09-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20230929_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
