# Generated by Django 3.2 on 2023-10-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('order', '0024_auto_20230929_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAssistanceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_scheduled_gte', models.DateField(blank=True, null=True)),
                ('date_scheduled_lte', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancestatus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancetype')),
            ],
        ),
    ]
