# Generated by Django 3.2 on 2023-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_orderassistancefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
