# Generated by Django 3.2 on 2023-10-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productfile'),
        ('order', '0025_orderassistancefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
