# Generated by Django 3.2 on 2023-10-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20231011_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='real_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='real_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
