# Generated by Django 3.2 on 2023-10-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20231009_1735'),
        ('order', '0027_auto_20231011_2113'),
    ]

    operations = [
    ]
