# Generated by Django 3.2 on 2023-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_merge_0027_auto_20231009_1735_0027_auto_20231011_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='expedition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='expedition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
