# Generated by Django 3.2 on 2023-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20231013_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='complement',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='complement',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complement',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='complement',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
    ]
