# Generated by Django 3.2 on 2023-11-21 14:05

import apps.order.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0030_auto_20231025_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommitmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.order.models.OrderCommitmentFile.upload_to_path, validators=[apps.order.models.OrderCommitmentFile.validate_file_size])),
                ('name', models.CharField(max_length=100)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.ordercommitment')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOrderCommitmentFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('file', models.TextField(blank=True, max_length=100, null=True, validators=[apps.order.models.OrderCommitmentFile.validate_file_size])),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('commitment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order commitment file',
                'verbose_name_plural': 'historical order commitment files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
