# Generated by Django 3.2 on 2023-12-08 13:43

from django.db import migrations, models

def populate_commitment_from_delivery(apps, schema_editor):
    OrderDelivery = apps.get_model('order', 'OrderDelivery')
    OrderCommitment = apps.get_model('order', 'OrderCommitment')

    for delivery in OrderDelivery.objects.all():

        if delivery:
            commitment = OrderCommitment.objects.get(id=delivery.commitment.id)

            commitment.note_number = delivery.note_number
            commitment.billing_date = delivery.billing_date
            commitment.pay_date = delivery.pay_date
            commitment.real_pay_date = delivery.real_pay_date
            commitment.annotation_invoicing = delivery.annotation_invoicing

            commitment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_historicalordercommitmentfile_ordercommitmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordercommitment',
            name='annotation_invoicing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalordercommitment',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalordercommitment',
            name='note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalordercommitment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalordercommitment',
            name='real_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='annotation_invoicing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='real_pay_date',
            field=models.DateField(blank=True, null=True),
        ),

        migrations.RunPython(populate_commitment_from_delivery),

        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='real_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
