# Generated by Django 3.2 on 2023-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_populate_commitment_from_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordercommitmentitemproduct',
            name='fob_freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ordercommitmentitemproduct',
            name='fob_freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
