# Generated by Django 3.2 on 2023-12-05 20:24

from django.db import migrations, models
import django.db.models.deletion

def populate_order_from_commitment(apps, schema_editor):
    OrderDelivery = apps.get_model('order', 'OrderDelivery')
    Order = apps.get_model('order', 'Order')

    for order_delivery in OrderDelivery.objects.all():

        commitment = order_delivery.commitment
        if commitment:
            order = Order.objects.get(id=commitment.order.id)
            order_delivery.order = order
            order_delivery.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_populate_commitment_from_delivery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together=set(),
        ),
        
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order'),
        ),

        migrations.AddField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),

        migrations.RunPython(populate_order_from_commitment),
        
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
