# Generated by Django 3.2 on 2023-12-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_populate_order_from_commitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='historicalorderdeliveryfilter',
            name='commitment_number',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryfilter',
            name='commitment_number',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='commitment',
        ),
    ]
