# Generated by Django 3.2 on 2023-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_remove_commitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='delivery_number',
        ),
        migrations.RemoveField(
            model_name='historicalorderdeliveryfilter',
            name='delivery_number',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryfilter',
            name='delivery_number',
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='date_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='date_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='delivery_number',
        ),
    ]
