# Generated by Django 3.2 on 2023-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20231206_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdeliveryfilter',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryfilter',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
