# Generated by Django 3.2 on 2023-12-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20231206_1807'),
        ('order', '0036_auto_20231206_1756'),
    ]

    operations = [
    ]
