# Generated by Django 3.2 on 2023-12-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_merge_0033_auto_20231206_1807_0036_auto_20231206_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='annotation_invoicing',
        ),
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='historicalorderdelivery',
            name='real_pay_date',
        ),
        migrations.RemoveField(
            model_name='historicalorderdeliveryfilter',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='historicalorderdeliveryfilter',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='historicalorderdeliveryfilter',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='annotation_invoicing',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='real_pay_date',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryfilter',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryfilter',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryfilter',
            name='pay_date',
        ),
    ]
