# Generated by Django 3.2 on 2023-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20231208_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordercommitment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
