# Generated by Django 3.2 on 2023-12-11 18:13

from django.db import migrations

def create_initial_audit_instance(apps, schema_editor):
    OrderAuditPercentage = apps.get_model('order', 'OrderAuditPercentage')
    OrderAuditPercentage.objects.get_or_create(pk=1)

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_historicalorderauditpercentage_orderauditpercentage'),
    ]

    operations = [
        migrations.RunPython(create_initial_audit_instance),
    ]
