# Generated by Django 3.2 on 2023-12-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20231208_1957'),
        ('order', '0040_populate_initial_audit_instance'),
    ]

    operations = [
    ]
