# Generated by Django 3.2 on 2023-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_merge_20231211_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='last_audit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('audit', 'Audit'), ('done', 'Done'), ('declined', 'Declined')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='last_audit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('audit', 'Audit'), ('done', 'Done'), ('declined', 'Declined')], default='idle', max_length=20),
        ),
    ]
