# Generated by Django 3.2 on 2023-12-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20231211_1938'),
        ('order', '0041_merge_20231211_1854'),
    ]

    operations = [
    ]
