# Generated by Django 3.2 on 2023-12-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_merge_20231213_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='is_done',
        ),
        migrations.AddField(
            model_name='historicalordercommitment',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('done', 'Done')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('done', 'Done')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdeliveryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_delivery', to='order.ordercommitmentitem'),
        ),
    ]
