# Generated by Django 3.2 on 2023-12-14 17:31

from django.db import migrations

def change_order_situation(apps, schema_editor):
    OrderDelivery = apps.get_model('order', 'OrderDelivery')

    for delivery in OrderDelivery.objects.all():

        if delivery:
            if delivery.is_done:
                delivery.situation = 'done'
                
                delivery.save()

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20231213_1923'),
    ]

    operations = [
        migrations.RunPython(change_order_situation),
        
        migrations.RemoveField(
            name='is_done',
            model_name='orderdelivery',
        ),

        migrations.RemoveField(
            name='is_done',
            model_name='historicalorderdelivery',
        ),
    ]
