# Generated by Django 3.2 on 2023-12-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20231214_1232'),
        ('order', '0043_change_order_situation'),
    ]

    operations = [
    ]
