# Generated by Django 3.2 on 2023-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_merge_20231214_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordercommitment',
            name='last_audit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='last_audit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalordercommitment',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('done', 'Done'), ('audit', 'Audit'), ('declined', 'Declined')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercommitment',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('done', 'Done'), ('audit', 'Audit'), ('declined', 'Declined')], default='idle', max_length=20),
        ),
    ]
