# Generated by Django 3.2 on 2023-12-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20231215_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='last_audit_value',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='last_audit_value',
        ),
        migrations.AddField(
            model_name='historicalordercommitmentitemproduct',
            name='last_audit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ordercommitmentitemproduct',
            name='last_audit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
