# Generated by Django 3.2 on 2024-01-11 20:48

import apps.order.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0046_auto_20231219_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('invoicing_date', models.DateField(blank=True, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('real_pay_date', models.DateField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('situation', models.CharField(choices=[('idle', 'Idle'), ('audit', 'Audit'), ('done', 'Done'), ('declined', 'Declined')], default='idle', max_length=20)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordercommitment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInvoicingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('invoicing', 'Invoicing'), ('released', 'Released'), ('audit', 'Audit'), ('done', 'Done'), ('declined', 'Declined')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('invoicing', 'Invoicing'), ('released', 'Released'), ('audit', 'Audit'), ('done', 'Done'), ('declined', 'Declined')], default='idle', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderInvoicingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.order.models.OrderInvoicingFile.upload_to_path, validators=[apps.order.models.OrderInvoicingFile.validate_file_size])),
                ('name', models.CharField(max_length=100)),
                ('invoicing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.orderinvoicing')),
            ],
        ),
        migrations.AddField(
            model_name='orderinvoicing',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdelivery'),
        ),
        migrations.AddField(
            model_name='orderinvoicing',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderinvoicingstatus'),
        ),
        migrations.CreateModel(
            name='HistoricalOrderInvoicingStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('initial', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order invoicing status',
                'verbose_name_plural': 'historical order invoicing statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderInvoicingFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('file', models.TextField(blank=True, max_length=100, null=True, validators=[apps.order.models.OrderInvoicingFile.validate_file_size])),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoicing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinvoicing')),
            ],
            options={
                'verbose_name': 'historical order invoicing file',
                'verbose_name_plural': 'historical order invoicing files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderInvoicing',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('invoicing_date', models.DateField(blank=True, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('real_pay_date', models.DateField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('situation', models.CharField(choices=[('idle', 'Idle'), ('audit', 'Audit'), ('done', 'Done'), ('declined', 'Declined')], default='idle', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('commitment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitment')),
                ('delivery', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdelivery')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinvoicingstatus')),
            ],
            options={
                'verbose_name': 'historical order invoicing',
                'verbose_name_plural': 'historical order invoicings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
