# Generated by Django 3.2 on 2024-01-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20240111_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderinvoicing',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('released', 'Released'), ('done', 'Done')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderinvoicing',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('released', 'Released'), ('done', 'Done')], default='idle', max_length=20),
        ),
    ]
