# Generated by Django 3.2 on 2024-01-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_auto_20240116_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderinvoicing',
            unique_together={('delivery', 'commitment')},
        ),
    ]
