# Generated by Django 3.2 on 2024-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_alter_orderinvoicing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('invoicing', 'Invoicing'), ('released', 'Released'), ('declined', 'Declined'), ('audit', 'Audit'), ('done', 'Done')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='situation',
            field=models.CharField(choices=[('idle', 'Idle'), ('invoicing', 'Invoicing'), ('released', 'Released'), ('declined', 'Declined'), ('audit', 'Audit'), ('done', 'Done')], default='idle', max_length=20),
        ),
    ]
