# Generated by Django 3.2 on 2024-01-26 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_carrier_complement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_alter_company_complement'),
        ('order', '0050_auto_20240124_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoicingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('delivery_number', models.CharField(blank=True, max_length=100, null=True)),
                ('commitment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nf_payed', models.BooleanField(null=True)),
                ('date_delivery_gte', models.DateField(blank=True, null=True)),
                ('date_delivery_lte', models.DateField(blank=True, null=True)),
                ('invoicing_delivery_date_gte', models.DateField(blank=True, null=True)),
                ('invoicing_delivery_date_lte', models.DateField(blank=True, null=True)),
                ('real_pay_date_gte', models.DateField(blank=True, null=True)),
                ('real_pay_date_lte', models.DateField(blank=True, null=True)),
                ('invoicing_date_gte', models.DateField(blank=True, null=True)),
                ('invoicing_date_lte', models.DateField(blank=True, null=True)),
                ('situation', models.CharField(blank=True, max_length=20, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.carrier')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderinvoicingstatus')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOrderInvoicingFilter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('delivery_number', models.CharField(blank=True, max_length=100, null=True)),
                ('commitment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nf_payed', models.BooleanField(null=True)),
                ('date_delivery_gte', models.DateField(blank=True, null=True)),
                ('date_delivery_lte', models.DateField(blank=True, null=True)),
                ('invoicing_delivery_date_gte', models.DateField(blank=True, null=True)),
                ('invoicing_delivery_date_lte', models.DateField(blank=True, null=True)),
                ('real_pay_date_gte', models.DateField(blank=True, null=True)),
                ('real_pay_date_lte', models.DateField(blank=True, null=True)),
                ('invoicing_date_gte', models.DateField(blank=True, null=True)),
                ('invoicing_date_lte', models.DateField(blank=True, null=True)),
                ('situation', models.CharField(blank=True, max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.carrier')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinvoicingstatus')),
            ],
            options={
                'verbose_name': 'historical order invoicing filter',
                'verbose_name_plural': 'historical order invoicing filters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
