# Generated by Django 3.2 on 2024-01-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_historicalorderinvoicingfilter_orderinvoicingfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoicing',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='orderinvoicing',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderdelivery'),
        ),
    ]
