# Generated by Django 3.2 on 2024-01-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_complement'),
        ('order', '0052_auto_20240126_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderinvoicingfilter',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AddField(
            model_name='orderinvoicingfilter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
    ]
