# Generated by Django 3.2 on 2024-04-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_auto_20240130_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='annotation_invoicing',
        ),
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='historicalordercommitment',
            name='real_pay_date',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='annotation_invoicing',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='ordercommitment',
            name='real_pay_date',
        ),
    ]
