# Generated by Django 3.2 on 2024-04-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20240412_0203'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id'], name='order_order_id_11b17b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-id'], name='order_order_id_426e67_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_expiration'], name='order_order_date_ex_f61a61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date_expiration'], name='order_order_date_ex_8e57c4_idx'),
        ),
    ]
