# Generated by Django 3.2 on 2024-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20240412_0219'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['id'], name='order_order_id_9fd11c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['-id'], name='order_order_id_4588d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['date_delivery'], name='order_order_date_de_8b7377_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['-date_delivery'], name='order_order_date_de_852c00_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['date_expiration'], name='order_order_date_ex_8be05f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['-date_expiration'], name='order_order_date_ex_e31487_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercommitment',
            index=models.Index(fields=['situation'], name='order_order_situati_1d2992_idx'),
        ),
    ]
