# Generated by Django 3.2 on 2024-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20240412_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordercommitmentfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalorderfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordercommitmentfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfile',
            name='name',
            field=models.TextField(),
        ),
    ]
