# Generated by Django 3.2 on 2024-04-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_auto_20240412_0257'),
        ('order', '0056_auto_20240412_1905'),
    ]

    operations = [
    ]
