# Generated by Django 3.2 on 2024-04-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_merge_0056_auto_20240412_0257_0056_auto_20240412_1905'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordercommitment',
            name='order_order_id_9fd11c_idx',
        ),
        migrations.AddField(
            model_name='historicalorderinvoicing',
            name='liquid_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalorderinvoicing',
            name='total_items',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalorderinvoicing',
            name='total_nf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderinvoicing',
            name='liquid_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderinvoicing',
            name='total_items',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderinvoicing',
            name='total_nf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
