# Generated by Django 3.2 on 2024-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_populate_invoicing'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['id'], name='order_order_id_43636d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['-id'], name='order_order_id_952509_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['date_delivery'], name='order_order_date_de_87c30b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['-date_delivery'], name='order_order_date_de_b908b0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['invoicing_delivery_date'], name='order_order_invoici_1a83b6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['-invoicing_delivery_date'], name='order_order_invoici_8f8230_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['situation'], name='order_order_situati_045c5b_idx'),
        ),
    ]
