# Generated by Django 3.2 on 2024-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20240416_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderauditpercentage',
            name='commitment_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderauditpercentage',
            name='commitment_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
