# Generated by Django 3.2 on 2024-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_auto_20240425_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordercommitmentitem',
            name='last_audit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ordercommitmentitem',
            name='last_audit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
