# Generated by Django 3.2 on 2024-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('order', '0062_auto_20240425_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderassistancestatus',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderauditpercentage',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalordercommitmentstatus',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderdeliverystatus',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderinterest',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderinvoicingstatus',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='orderassistancestatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_status', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderauditpercentage',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_audit', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercommitmentstatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commitment_status', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdeliverystatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinterest',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_interest', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinvoicingstatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_status', to='accounts.account'),
            preserve_default=False,
        ),
    ]
