# Generated by Django 3.2 on 2024-05-24 00:24

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20240523_0515'),
        ('accounts', '0009_alter_account_managers'),
        ('transport', '0007_auto_20240523_0520'),
        ('contract', '0019_auto_20240523_2230'),
        ('company', '0009_auto_20240523_0522'),
        ('client', '0003_auto_20240518_0027'),
        ('order', '0063_auto_20240517_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderassistance',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderassistancefilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderassistancestatus',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderassistancetype',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitment',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitmentfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitmentfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitmentitem',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitmentitemproduct',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitmentstatus',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdelivery',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdeliveryfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdeliveryfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdeliveryfreightcotation',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdeliveryitem',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdeliverystatus',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinterest',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinvoicing',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinvoicingfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinvoicingfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinvoicingstatus',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderassistance',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderassistancetype',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalordercommitment',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalordercommitmentfile',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalordercommitmentitem',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalordercommitmentitemproduct',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderdelivery',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderdeliveryfile',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderdeliveryfilter',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderdeliveryfreightcotation',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderdeliveryitem',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderfile',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderinvoicing',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderinvoicingfile',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalorderinvoicingfilter',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderassistance',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderAssistance', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderassistancefilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderAssistanceFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderassistancetype',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderAssistanceType', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercommitment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderCommitment', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercommitmentfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderCommitmentFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercommitmentfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderCommitmentFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercommitmentitem',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderCommitmentItem', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercommitmentitemproduct',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderCommitmentItemProduct', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDelivery', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdeliveryfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDeliveryFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdeliveryfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDeliveryFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdeliveryfreightcotation',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDeliveryFreightCotation', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdeliveryitem',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDeliveryItem', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinvoicing',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderInvoicing', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinvoicingfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderInvoicingFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinvoicingfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderInvoicingFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalorderassistancestatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorderassistancetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalordercommitmentstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderassistancestatus',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderAssistanceStatus', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliverystatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorderinterest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderassistancefilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderassistancestatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderassistancetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercommitmentfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercommitmentstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliverystatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderinterest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderinvoicingstatus',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderInvoicingStatus', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='orderinvoicingstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ordercommitment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderinvoicing',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_id_account'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('contract', 'account'), name='unique_order_contract_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistance',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_assistance_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistancefilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_assistance_filter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistancefilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_assistance_filter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistancestatus',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_assistance_status_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistancestatus',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_assistance_status_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistancetype',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_assistance_type_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderassistancetype',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_assistance_type_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderauditpercentage',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_audit_percentage_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitment',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_commitment_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitment',
            constraint=models.UniqueConstraint(fields=('order', 'number', 'account'), name='unique_order_commitment_order_number_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentfile',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_commitment_file_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_commitment_filter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_commitment_filter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentitem',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_commitment_item_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentitemproduct',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_commitment_item_product_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentstatus',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_commitment_status_id_account'),
        ),
        migrations.AddConstraint(
            model_name='ordercommitmentstatus',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_commitment_status_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdelivery',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_delivery_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliveryfile',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_delivery_file_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliveryfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_delivery_filter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliveryfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_delivery_filter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliveryfreightcotation',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_delivery_freight_cotation_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliveryitem',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_delivery_item_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliverystatus',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_delivery_status_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderdeliverystatus',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_delivery_status_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderfile',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_file_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_filter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_filter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinterest',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_interest_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinterest',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_interest_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicing',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_invoicing_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicing',
            constraint=models.UniqueConstraint(fields=('delivery', 'commitment', 'account'), name='unique_order_invoicing_delivery_commitment_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicingfile',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_invoicing_file_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicingfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_invoicing_filter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicingfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_invoicing_filter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicingstatus',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_order_invoicing_status_id_account'),
        ),
        migrations.AddConstraint(
            model_name='orderinvoicingstatus',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_order_invoicing_status_name_account'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinterest'),
        ),
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order'),
        ),
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderassistancestatus'),
        ),
        migrations.AlterField(
            model_name='historicalorderassistance',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderassistancetype'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitment',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitment',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitment',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitmentstatus'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitmentfile',
            name='commitment',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitmentitem',
            name='commitment',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitmentitem',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitmentitemproduct',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitmentitem'),
        ),
        migrations.AlterField(
            model_name='historicalordercommitmentitemproduct',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractitemcompound'),
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order'),
        ),
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdeliverystatus'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfile',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfilter',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdeliverystatus'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfreightcotation',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryfreightcotation',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryitem',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='historicalorderdeliveryitem',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitmentitem'),
        ),
        migrations.AlterField(
            model_name='historicalorderfile',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicing',
            name='commitment',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicing',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicing',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinvoicingstatus'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfile',
            name='invoicing',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinvoicing'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfilter',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalorderinvoicingfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderinvoicingstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderinterest'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancestatus'),
        ),
        migrations.AlterField(
            model_name='orderassistance',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancetype'),
        ),
        migrations.AlterField(
            model_name='orderassistancefilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AlterField(
            model_name='orderassistancefilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancestatus'),
        ),
        migrations.AlterField(
            model_name='orderassistancefilter',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderassistancetype'),
        ),
        migrations.AlterField(
            model_name='ordercommitment',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='ordercommitment',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='order.order'),
        ),
        migrations.AlterField(
            model_name='ordercommitment',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitmentstatus'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentfile',
            name='commitment',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitmentstatus'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentitem',
            name='commitment',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentitem',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentitemproduct',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.ordercommitmentitem'),
        ),
        migrations.AlterField(
            model_name='ordercommitmentitemproduct',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractitemcompound'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderdeliverystatus'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfile',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfilter',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderdeliverystatus'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfreightcotation',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryfreightcotation',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryitem',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryitem',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_delivery', to='order.ordercommitmentitem'),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='order',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='client.client'),
        ),
        migrations.AlterField(
            model_name='orderfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='company.company'),
        ),
        migrations.AlterField(
            model_name='orderfilter',
            name='interest',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_filter', to='order.orderinterest'),
        ),
        migrations.AlterField(
            model_name='orderinvoicing',
            name='commitment',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ordercommitment'),
        ),
        migrations.AlterField(
            model_name='orderinvoicing',
            name='delivery',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderdelivery'),
        ),
        migrations.AlterField(
            model_name='orderinvoicing',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderinvoicingstatus'),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfile',
            name='invoicing',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='order.orderinvoicing'),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfilter',
            name='carrier',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.carrier'),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='orderinvoicingfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderinvoicingstatus'),
        ),
    ]
