# Generated by Django 3.2 on 2024-05-24 19:30

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20240524_0024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderassistancestatus',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ordercommitmentstatus',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdeliverystatus',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinterest',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderinvoicingstatus',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
