# Generated by Django 3.2 on 2024-05-31 19:29

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_auto_20240524_1930'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderassistancetype',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
