# Generated by Django 3.2 on 2023-12-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_carrier_complement'),
        ('supplier', '0004_alter_supplier_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='region_freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.freight'),
        ),
    ]
