# Generated by Django 3.2 on 2024-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('supplier', '0005_supplier_region_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_category', to='accounts.account'),
            preserve_default=False,
        ),
    ]
