# Generated by Django 3.2 on 2024-05-23 05:18

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20240517_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_supplier_category_id_account'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_supplier_category_name_account'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_supplier_id_account'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('cnpj', 'account'), name='unique_supplier_cnpj_account'),
        ),
    ]
