# Generated by Django 3.2 on 2024-05-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_alter_category_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='supplier.Category'),
        ),
    ]
