# Generated by Django 3.2 on 2023-08-21 01:40

import apps.contract.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productfile'),
        ('accounts', '0001_initial'),
        ('bidding', '0006_bidding_date_expiry_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('released', models.BooleanField(default=False)),
                ('bidding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='bidding.bidding')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unit', 'Unit'), ('compound', 'Compound'), ('lote', 'Lote')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('freight', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('margin_min', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('price_min', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contract.contract')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contract.contractitem')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingitem')),
            ],
            options={
                'unique_together': {('contract', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='ContractScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.contract.models.ContractFile.upload_to_path, validators=[apps.contract.models.ContractFile.validate_file_size])),
                ('name', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='contract.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractscope'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractstatus'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contracttype'),
        ),
        migrations.CreateModel(
            name='ContractItemCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='contract.contractitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingitemcompound')),
            ],
            options={
                'unique_together': {('item', 'reference', 'product')},
            },
        ),
    ]
