# Generated by Django 3.2 on 2023-08-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='released',
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('released', 'Released'), ('suspensed', 'Suspensed'), ('draft', 'Draf')], default='draft', max_length=10),
        ),
    ]
