# Generated by Django 3.2 on 2023-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20230823_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
