# Generated by Django 3.2 on 2023-08-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractfile',
            old_name='order',
            new_name='contract',
        ),
    ]
