# Generated by Django 3.2 on 2023-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_rename_order_contractfile_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('released', 'Released'), ('suspended', 'Suspended'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
