# Generated by Django 3.2 on 2023-08-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auto_20230816_2138'),
        ('contract', '0006_alter_contract_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('bidding', 'number')},
        ),
    ]
