# Generated by Django 3.2 on 2023-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
