# Generated by Django 3.2 on 2023-08-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auto_20230816_2138'),
        ('contract', '0008_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='bidding.bidding'),
        ),
    ]
