# Generated by Django 3.2 on 2023-08-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_difference'),
        ('client', '0001_initial'),
        ('contract', '0009_alter_contract_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContractFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_outdated', models.BooleanField(null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='client.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='company.company')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='contract.contractscope')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='contract.contractstatus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='contract.contracttype')),
            ],
        ),
    ]
