# Generated by Django 3.2 on 2023-09-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_historicalcontract_historicalcontractfile_historicalcontractfilter_historicalcontractitem_historical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_outdated',
        ),
        migrations.RemoveField(
            model_name='contractfilter',
            name='is_outdated',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='is_outdated',
        ),
        migrations.RemoveField(
            model_name='historicalcontractfilter',
            name='is_outdated',
        ),
    ]
