# Generated by Django 3.2 on 2023-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_auto_20230925_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfilter',
            name='is_outdated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcontractfilter',
            name='is_outdated',
            field=models.BooleanField(null=True),
        ),
    ]
