# Generated by Django 3.2 on 2023-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20230926_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfilter',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontractfilter',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
