# Generated by Django 3.2 on 2023-12-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20231013_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='fob_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontractitem',
            name='fob_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
