# Generated by Django 3.2 on 2024-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20231205_2125'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['date_start'], name='contract_co_date_st_69f914_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-date_start'], name='contract_co_date_st_b6b23f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['date_finish'], name='contract_co_date_fi_04ae8f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-date_finish'], name='contract_co_date_fi_634195_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['number'], name='contract_co_number_a9c87b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['state'], name='contract_co_state_0c35cd_idx'),
        ),
    ]
