# Generated by Django 3.2 on 2024-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20240412_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalcontractfile',
            name='name',
            field=models.TextField(),
        ),
    ]
