# Generated by Django 3.2 on 2024-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('contract', '0017_auto_20240412_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstatus',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_status', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontractstatus',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
    ]
