# Generated by Django 3.2 on 2024-05-23 22:30

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_managers'),
        ('company', '0009_auto_20240523_0522'),
        ('bidding', '0024_auto_20240610_0146'),
        ('client', '0003_auto_20240518_0027'),
        ('product', '0008_auto_20240523_0515'),
        ('contract', '0018_auto_20240517_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contract',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractfile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractitem',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractitemcompound',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractscope',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractstatus',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contracttype',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Contract', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractfile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContractFile', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContractFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractitem',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContractItem', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractitemcompound',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContractItemCompound', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractscope',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContractScope', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracttype',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContractType', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalcontractfile',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalcontractfilter',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalcontractitem',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalcontractitemcompound',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalcontractscope',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalcontracttype',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='contractfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractscope',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontractscope',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontractstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontracttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontractfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contractitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contractitemcompound',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('bidding', 'number', 'account'), name='unique_contract_bidding_number_account_account'),
        ),
        migrations.AddConstraint(
            model_name='contractfile',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_file_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contractfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_filter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contractfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_contract_filter_name_account'),
        ),
        migrations.AddConstraint(
            model_name='contractitem',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_item_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contractitem',
            constraint=models.UniqueConstraint(fields=('contract', 'reference', 'account'), name='unique_contract_item_contract_reference_account'),
        ),
        migrations.AddConstraint(
            model_name='contractitemcompound',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_item_compound_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contractitemcompound',
            constraint=models.UniqueConstraint(fields=('item', 'reference', 'product', 'account'), name='unique_contract_item_compound_item_reference_product_account'),
        ),
        migrations.AddConstraint(
            model_name='contractscope',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_scope_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contractscope',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_contract_scope_name_account'),
        ),
        migrations.AddConstraint(
            model_name='contractstatus',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_status_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contractstatus',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_contract_status_name_account'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_contract_type_id_account'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_contract_type_name_account'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='scope',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractscope'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contractstatus'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contracttype'),
        ),
        migrations.AlterField(
            model_name='contractfile',
            name='contract',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='client.client'),
        ),
        migrations.AlterField(
            model_name='contractfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='company.company'),
        ),
        migrations.AlterField(
            model_name='contractfilter',
            name='scope',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='contract.contractscope'),
        ),
        migrations.AlterField(
            model_name='contractfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='contract.contractstatus'),
        ),
        migrations.AlterField(
            model_name='contractfilter',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_filter', to='contract.contracttype'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='contract',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='parent',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='reference',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingitem'),
        ),
        migrations.AlterField(
            model_name='contractitemcompound',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='contractitemcompound',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='contractitemcompound',
            name='reference',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding.biddingitemcompound'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='bidding',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.bidding'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='scope',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractscope'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractstatus'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contracttype'),
        ),
        migrations.AlterField(
            model_name='historicalcontractfile',
            name='contract',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='historicalcontractfilter',
            name='client',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='historicalcontractfilter',
            name='company',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalcontractfilter',
            name='scope',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractscope'),
        ),
        migrations.AlterField(
            model_name='historicalcontractfilter',
            name='status',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractstatus'),
        ),
        migrations.AlterField(
            model_name='historicalcontractfilter',
            name='type',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contracttype'),
        ),
        migrations.AlterField(
            model_name='historicalcontractitem',
            name='contract',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='historicalcontractitem',
            name='parent',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='historicalcontractitem',
            name='reference',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingitem'),
        ),
        migrations.AlterField(
            model_name='historicalcontractitemcompound',
            name='item',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contractitem'),
        ),
        migrations.AlterField(
            model_name='historicalcontractitemcompound',
            name='product',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AlterField(
            model_name='historicalcontractitemcompound',
            name='reference',
            field=django_multitenant.fields.TenantForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bidding.biddingitemcompound'),
        ),
    ]
