# Generated by Django 3.2 on 2024-05-24 19:45

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_auto_20240523_2230'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contractstatus',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
