# Generated by Django 3.2 on 2024-05-28 02:22

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_alter_contractstatus_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contractscope',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contracttype',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
