# Generated by Django 3.2 on 2023-09-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('pncp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PncpFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.JSONField(blank=True, default=dict, null=True)),
                ('organ', models.JSONField(blank=True, default=dict, null=True)),
                ('unit', models.JSONField(blank=True, default=dict, null=True)),
                ('hiring_modalities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pncp_filter', to='pncp.hiringmodalitie')),
                ('powers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pncp_filter', to='pncp.powers')),
                ('spheres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pncp_filter', to='pncp.spheres')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pncp_filter', to='address.state')),
                ('type_calling_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pncp_filter', to='pncp.typecallinginstrument')),
            ],
        ),
    ]
