# Generated by Django 3.2 on 2024-05-30 18:25

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_managers'),
        ('pncp', '0002_pncpfilter'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pncpfilter',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='pncpfilter',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PncpFilter', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pncpfilter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pncpfilter',
            unique_together={('id', 'account')},
        ),
        migrations.AddConstraint(
            model_name='pncpfilter',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_pncpfilter_id_account'),
        ),
        migrations.AddConstraint(
            model_name='pncpfilter',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_pncpfilter_name_account'),
        ),
    ]
