# Generated by Django 3.2 on 2024-05-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pncp', '0003_auto_20240530_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pncpfilter',
            unique_together=set(),
        ),
    ]
    




    ZeroDivisionError ('division by zero')
    operations = [
        migrations.AlterUniqueTogether(
            name='pncpfilter',
            unique_together=set(),
        ),
    ]
    classmethod