#!/bin/bash

HERE=$(dirname $(readlink -f "$0"))
ROOT=$(realpath $HERE/..)

set -x

cd $ROOT

python manage.py makemigrations address
python manage.py makemigrations accounts
python manage.py makemigrations permission
python manage.py makemigrations company
python manage.py makemigrations client
python manage.py makemigrations bidding
python manage.py makemigrations supplier
python manage.py makemigrations product
python manage.py makemigrations transport
python manage.py makemigrations contact
python manage.py makemigrations messager
python manage.py makemigrations contract
python manage.py makemigrations order
python manage.py makemigrations pncp
python manage.py makemigrations commission
python manage.py makemigrations metadata

find apps -type f -name '0*.py' -exec sed -i 's/# Generated by Django.*//g' {} \;
