# Generated by Django 3.2 on 2023-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_alter_permissionoptions_app_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionoptions',
            name='app_option',
            field=models.CharField(choices=[('Default', 'Padrão'), ('User', 'Usuários'), ('Permission', 'Permissões'), ('Company', 'Empresas'), ('Client', 'Clientes'), ('Bidding', 'Licitações'), ('BiddingSettings', 'Configurações de Licitações'), ('Supplier', 'Fornecedores'), ('SupplierSettings', 'Configurações de Fornecedores'), ('Product', 'Produtos'), ('ProductSettings', 'Configurações de Produtos'), ('Transport', 'Transporte'), ('TransportSettings', 'Configurações de Transporte'), ('Order', 'Pedidos'), ('OrderSettings', 'Configurações de Pedidos'), ('Contract', 'Contratos'), ('ContractSettings', 'Configurações de Contratos')], default='Default', max_length=50, verbose_name='Modulos'),
        ),
    ]
