# Generated by Django 3.2 on 2023-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_alter_permissionoptions_app_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepermissions',
            name='audit_commitment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepermissions',
            name='audit_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
