# Generated by Django 3.2 on 2024-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240517_1441'),
        ('permission', '0006_auto_20231207_2014'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permissionoptions',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profilepermissions',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='permissionoptions',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PermissionOptions', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepermissions',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePermissions', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionoptions',
            name='app_option',
            field=models.CharField(choices=[('Default', 'Padrão'), ('User', 'Usuários'), ('Permission', 'Permissões'), ('Company', 'Empresas'), ('Client', 'Clientes'), ('Bidding', 'Licitações'), ('BiddingSettings', 'Configurações de Licitações'), ('Supplier', 'Fornecedores'), ('SupplierSettings', 'Configurações de Fornecedores'), ('Product', 'Produtos'), ('ProductSettings', 'Configurações de Produtos'), ('Transport', 'Transporte'), ('TransportSettings', 'Configurações de Transporte'), ('Order', 'Pedidos'), ('OrderSettings', 'Configurações de Pedidos'), ('Contract', 'Contratos'), ('ContractSettings', 'Configurações de Contratos'), ('Commission', 'Comissões'), ('Report', 'Relatórios')], default='Default', max_length=50, verbose_name='Modulos'),
        ),
    ]
