# Generated by Django 3.2 on 2024-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0007_auto_20240517_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepermissions',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='permissionoptions',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_permission_options_id_account'),
        ),
        migrations.AddConstraint(
            model_name='profilepermissions',
            constraint=models.UniqueConstraint(fields=('id', 'account'), name='unique_profile_permission_id_account'),
        ),
        migrations.AddConstraint(
            model_name='profilepermissions',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='unique_profile_permission_name_account'),
        ),
    ]
