# Generated by Django 3.2 on 2024-05-27 01:20

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_auto_20240523_0442'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permissionoptions',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profilepermissions',
            managers=[
                ('objects', apps.accounts.models.AccountTenantManager()),
            ],
        ),
    ]
